# Generated by Django 6.0.5 on 2026-06-15 12:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departments', '0001_initial'),
        ('reports', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicateflag',
            name='duplicate_report',
            field=models.ForeignKey(help_text='The suspected duplicate/newer report', on_delete=django.db.models.deletion.CASCADE, related_name='duplicate_flags', to='reports.report'),
        ),
        migrations.AlterField(
            model_name='duplicateflag',
            name='original_report',
            field=models.ForeignKey(help_text='The original/earlier report', on_delete=django.db.models.deletion.CASCADE, related_name='original_flags', to='reports.report'),
        ),
        
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['county', 'status'], name='reports_rep_county_3c723b_idx'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['citizen', 'created_at'], name='reports_rep_citizen_613ee9_idx'),
        ),
    ]
