# Generated by Django 5.2.1 on 2026-07-01 11:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_alter_duplicateflag_duplicate_report_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duplicateflag',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='category',
            field=models.CharField(choices=[('roads', 'Roads'), ('water', 'Water'), ('bridges', 'Bridges'), ('streetlights', 'Streetlights'), ('public_facilities', 'Public Facilities'), ('safety', 'Safety/crime'), ('other', 'Other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='report',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, db_index=True, geography=True, null=True, srid=4326),
        ),
        migrations.AlterField(
            model_name='reportstatus',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
