# Generated by Django 5.2.1 on 2026-07-01 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_duplicateflag_id_alter_report_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='photo_reference',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]